IF OBJECT_ID('Sale') IS NOT NULL DROP TABLE SALE;
IF OBJECT_ID('Product') IS NOT NULL DROP TABLE PRODUCT;
IF OBJECT_ID('Customer') IS NOT NULL DROP TABLE CUSTOMER;
IF OBJECT_ID('Location') IS NOT NULL DROP TABLE LOCATION;
GO
CREATE TABLE CUSTOMER0136 (
CUSTID INT
, CUSTNAME  NVARCHAR(100)
, SALES_YTD INT
, STATUS    NVARCHAR(7)
, PRIMARY KEY     (CUSTID) );

CREATE TABLE PRODUCT0136 (
PRODID INT
, PRODNAME  NVARCHAR(100)
, SELLING_PRICE   MONEY
, SALES_YTD MONEY
, PRIMARY KEY     (PRODID));

CREATE TABLE SALE0136 (
SALEID INT
, CUSTID    INT
, PRODID    INT
, QTY INT
, PRICE     MONEY
, SALEDATE  DATE
, PRIMARY KEY     (SALEID)
, FOREIGN KEY     (CUSTID) REFERENCES CUSTOMER
, FOREIGN KEY     (PRODID) REFERENCES PRODUCT);

CREATE TABLE LOCATION0136 (
LOCID     NVARCHAR(5)
, MINQTY    INTEGER
, MAXQTY    INTEGER
, PRIMARY KEY     (LOCID)
, CONSTRAINT CHECK_LOCID_LENGTH CHECK (LEN(LOCID) = 5)
, CONSTRAINT CHECK_MINQTY_RANGE CHECK (MINQTY BETWEEN 0 AND 999)
, CONSTRAINT CHECK_MAXQTY_RANGE CHECK (MAXQTY BETWEEN 0 AND 999)
, CONSTRAINT CHECK_MAXQTY_GREATER_MIXQTY CHECK (MAXQTY >= MINQTY));
IF OBJECT_ID('SALE_SEQ') IS NOT NULL DROP SEQUENCE SALE_SEQ;
CREATE SEQUENCE SALE_SEQ;

GO

create PROCEDURE ADD_CUSTOMER0136 @pcustid INT,@pcustname nvarchar(100) as 
BEGIN
INSERT INTO CUSTOMER0136(CUSTID,CUSTNAME,SALES_YTD,STATUS) VALUES (@pcustid,@pcustname,0,'OK');
END;

go

create PROCEDURE DELETE_ALL_CUSTOMERS0136 as 
BEGIN
DECLARE @NumOfRows Int; 
SELECT @NumOfRows = count(*) FROM CUSTOMER0136; 
DELETE FROM CUSTOMER0136 ;
SELECT CONCAT(@NumOfRows);
END;

GO

create PROCEDURE ADD_PRODUCT0136 @pprodid Int,@pprodname nvarchar,@pprice money as 
BEGIN
INSERT INTO PRODUCT0136(PRODID,PRODNAME,SELLING_PRICE,SALES_YTD) VALUES (@pprodid,@pprodname,@pprice,0);
END;

GO

create PROCEDURE DELETE_ALL_PRODUCTS_FROM_DB0136 as 
BEGIN
DECLARE @NumOfRows Int; 
SELECT @NumOfRows = count(*) FROM PRODUCT0136;
DELETE FROM PRODUCT0136;
SELECT CONCAT(@NumOfRows);
END;

GO

create PROCEDURE GET_CUSTOMER_STRING @pcustid Int as 
BEGIN
DECLARE @NameOfCust nvarchar(100);
SET @NameOfCust = (SELECT CUSTNAME FROM CUSTOMER0136 WHERE CUSTID = @pcustid);
DECLARE @SalesOfCust INT;
SET @SalesOfCust = (SELECT SALES_YTD FROM CUSTOMER0136 WHERE CUSTID = @pcustid);
DECLARE @StatusOfCust NVARCHAR(7);
SET @StatusOfCust = (SELECT STATUS FROM CUSTOMER0136 WHERE CUSTID = @pcustid);
SELECT CONCAT('id of customer'+ @pcustid + 'name of customer' + @NameOfCust + 'sales of customer' + @SalesOfCust + 'status of customer' + @StatusOfCust + ';');
END;